NUM_DISPLACEMENT = "num_displacement"
ANALYTICAL_DISPLACEMENT = "analytical_displacement"
X_COORD = "x"
NUM_STRAIN = "num_strain"
ANALYTICAL_STRAIN = "analytical_strain"
ERROR_SQUARED = "error_squared"
